version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: studymatch
      POSTGRES_PASSWORD: studymatch
      POSTGRES_DB: studymatch
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studymatch -d studymatch"]
      interval: 2s
      timeout: 2s
      retries: 15
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://studymatch:studymatch@db:5432/studymatch
      JWT_SECRET: devsecretchangeme
      JWT_ALG: HS256
      CORS_ORIGINS: '["*"]'
      REDIS_URL: redis://redis:6379/0
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
volumes:
  db_data:
